CREATE TABLE STATE
(STATE_ID INT PRIMARY key,
STATE_NM VARCHAR(20),
STATE_CAPITAL VARCHAR(20),
RULING_PARTY VARCHAR(20))

CREATE TABLE CITY1
(CITY_ID INT PRIMARY KEY,
CITY_NM VARCHAR(20),
CITY_POP INT,
STATE_ID INT)

ALTER TABLE CITY1
ADD CONSTRAINT FK_STATEID
FOREIGN KEY(STATE_ID) REFERENCES STATE(STATE_ID)

INSERT INTO STATE VALUES(100, 'KARNATAKA', 'BANGLORE', 'BJP');
INSERT INTO STATE VALUES(101, 'TAMIL NADU', 'CHENNAI', 'DMK');
INSERT INTO STATE VALUES(102, 'TELANGANA', 'HYDERABAD', 'TRS');

INSERT INTO CITY1 VALUES(50, 'BANGLORE', 12765000, 100);
INSERT INTO CITY1 VALUES(51, 'MYSORE', 1234992, 100);
INSERT INTO CITY1 VALUES(52, 'CHENNAI', 11235018, 101);
INSERT INTO CITY1 VALUES(53, 'HUBLI', 1136923, 100);
INSERT INTO CITY1 VALUES(54, 'COIMBATORE', 2860445,101);
INSERT INTO CITY1 VALUES(55, 'HYDERABAD', 10268653, 102);

SELECT * FROM STATE

SELECT * FROM CITY1


SELECT TEMP1.STATE_NM STATE_NAME, CITY_NM CITY_NAME, CITY_POP CITY_POPULATION, STATE_POPULATION 
FROM 
(SELECT STATE_NM, CITY_NM, CITY_POP
FROM STATE S INNER JOIN CITY1 C 
ON S.STATE_ID=C.STATE_ID)TEMP1
INNER JOIN
(SELECT STATE_NM, SUM(CITY_POP) STATE_POPULATION 
FROM STATE S INNER JOIN CITY1 C 
ON S.STATE_ID=C.STATE_ID
GROUP BY STATE_NM)TEMP2
ON TEMP1.STATE_NM=TEMP2.STATE_NM
ORDER BY TEMP1.STATE_NM


SELECT STATE_NM, CITY_NM, CITY_POP 
FROM STATE S INNER JOIN CITY1 C 
ON S.STATE_ID=C.STATE_ID
ORDER BY STATE_NM, CITY_POP DESC

